# Generated by Django 5.0.6 on 2024-10-05 11:33

from django.db import migrations, models

 
class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_datananas'),
    ]

    operations = [
        migrations.AddField(
            model_name='datananas',
            name='gambar',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
