# Generated by Django 5.1.3 on 2025-01-09

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_datananas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatKlasifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.IntegerField()),
                ('green', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('brix', models.FloatField()),
                ('label', models.CharField(max_length=10)),  # Label lebih fleksibel, panjang 10
                ('gambar', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),  # Timestamp otomatis
            ],
        ),
    ]
