# Generated by Django <version> on <date>

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_gambar_datananas'),
        ('administrator', '0004_riwayat_klasifikasi'),
    ]

    operations = [
    ]
