# Generated by Django 5.1.3 on 2025-01-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_remove_brix_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatklasifikasi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='riwayatklasifikasi',
            name='gambar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
